/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosocketjavaesp8266;
import java.sql.*;
import java.sql.Connection;
//import java.sql.PreparedStatement;
//import com.mysql.jdbc.PreparedStatement;
//import java.sql.Statement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Municipio de Gye
 */
public class Login extends javax.swing.JFrame {

    basedata bd = new basedata(); 
    Connection cc = bd.conectar();
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        jPanelchange.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    
    public boolean acceder (String user, String clave){
        boolean cond=false;
        String capt="";
        String pwd="";
        String sql = "SELECT * FROM usuario WHERE nick='"+user+"' AND password='"+clave+"' ";
        try {
            Statement st = cc.createStatement();
            ResultSet rs = st.executeQuery(sql);
            /*while(rs.next()){
                if(user.equalsIgnoreCase("nick") && clave.equalsIgnoreCase("password")){
                    JOptionPane.showMessageDialog(this,"BIENVENIDO: "+user);
                } else{
                    JOptionPane.showMessageDialog(this,"USUARIO ERRÓNEO");
                }
            }*/
            while(rs.next()){
                capt= rs.getString("nick");
                pwd = rs.getString("password");
                if(user.equals(capt) && clave.equals(pwd)){
                    JOptionPane.showMessageDialog(this,"BIENVENIDO "+user+"!!");
                    cond=true;
                } else {
                    JOptionPane.showMessageDialog(null,"INCORRECTO");
                }
                
                
                //cond=false;
                /*else if(capt.equals("Invitado")){
                    JOptionPane.showMessageDialog(rootPane,"INVITADO");
                } else {
                    JOptionPane.showMessageDialog(this,"NO EXISTE");
                }*/
                
                //if(!capt.equals("Administrador") && !capt.equals("Invitado")){
                  //  JOptionPane.showMessageDialog(this,"NO EXISTE");
                //}
                
                //if(user=="" || clave==""){
                  //  JOptionPane.showMessageDialog(this,"INGRESE DATOS");
                //}
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
         return cond;
        
    }
    
    
    public void create_user (String user, String clave, String tipo){
        String mysql="INSERT INTO usuario (nick, password, tipoUsuario)"+ "values (?,?,?)";
        try {
            Statement st = cc.createStatement();
            PreparedStatement insertar = cc.prepareStatement(mysql);
            
           insertar.setString(1,user);
           insertar.setString(2,clave);
           insertar.setString(3,tipo);
           insertar.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanellogin = new javax.swing.JPanel();
        jLabelicon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelchange = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanellogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unnameddef.png"))); // NOI18N
        jPanellogin.add(jLabelicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 220));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("USUARIO: ");
        jPanellogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 90, 20));
        jPanellogin.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("CONTRASEÑA:");
        jPanellogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 120, 20));

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-user222.png"))); // NOI18N
        jButton1.setText("REGISTRARSE");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanellogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 140, 40));

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user1.png"))); // NOI18N
        jButton2.setText("INICIAR SESIÓN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanellogin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 150, 30));
        jPanellogin.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 120, -1));

        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit1.png"))); // NOI18N
        jButton4.setText("SALIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanellogin.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondologin2.jpg"))); // NOI18N
        jLabel1.setText("    ");
        jPanellogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        getContentPane().add(jPanellogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelchange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-user222.png"))); // NOI18N
        jButton3.setText("CREAR CUENTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelchange.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 170, 40));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("REGISTRARSE");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelchange.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 110, 30));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setText("TIPO DE USUARIO");
        jPanelchange.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanelchange.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 130, 30));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setText("CONFIRME SU CONTRASEÑA");
        jPanelchange.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("NOMBRE DE USUARIO");
        jPanelchange.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setText("NUEVA CONTRASEÑA");
        jPanelchange.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Invitado" }));
        jPanelchange.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 130, 20));
        jPanelchange.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 130, 30));
        jPanelchange.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 30));

        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras1.png"))); // NOI18N
        jButton5.setText("CANCELAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelchange.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondologin2.jpg"))); // NOI18N
        jPanelchange.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        getContentPane().add(jPanelchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String a = jTextField1.getText();
        String b = new String(jPasswordField1.getPassword());
        if(acceder(a,b) == true){
           //Interfaz i = new Interfaz();
           //i.setVisible(true);
           //this.setVisible(false);
           //new Login().setVisible(false);
          this.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanellogin.setVisible(false);
        jPanelchange.setVisible(true);
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String us = jTextField2.getText();
        String pw = new String(jPasswordField2.getPassword());
        String pw2 = new String(jPasswordField3.getPassword());
        String comb = jComboBox1.getSelectedItem().toString();  
        if(String.valueOf(jPasswordField2.getPassword()).equals(String.valueOf(jPasswordField3.getPassword()))){
        create_user(us,pw,comb);
        jPanelchange.setVisible(false);
        jPanellogin.setVisible(true);
        }
        else{
            jPasswordField2.setText("");
            jPasswordField3.setText("");
            JOptionPane.showMessageDialog(null,"VALIDACIÓN INCORRECTA DE LA CONTRASEÑA");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanelchange.setVisible(false);
        jPanellogin.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                //new Login().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelicon;
    private javax.swing.JPanel jPanelchange;
    private javax.swing.JPanel jPanellogin;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
