/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosocketjavaesp8266;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.DataInputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import proyectosocketjavaesp8266.Misocket;

/**
 *
 * @author Cmaster
 */
public class prueba extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form prueba
     */
    XYSeries series = new XYSeries("Sensor Electrocardiograma");
		XYSeriesCollection dataset = new XYSeriesCollection(series);
		JFreeChart chart = ChartFactory.createXYLineChart("Sensor", "Tiempo (Segundos)", "Lectura", dataset, PlotOrientation.VERTICAL,true,true,false);
                Thread Hilo = new Thread(this);
                 int x=0;
                 //hola
                 
    public prueba() {
        initComponents();
        
                pane.removeAll();
		pane.add(new ChartPanel(chart), BorderLayout.CENTER);
                pane.validate();
                Hilo.start();
                
                BotonParar.setVisible(false);
                botonComenzar.setVisible(true);
         
            
                //
    }
    /*
    
    wdewdwe
    */
    

    //public
       double i =0.0;
       int ss=0;
    public void datos(){
        double numero;
        i++;
        numero =  (Math.random()*1024)+1;
        series.add(i,1023-numero);
        if(i>10){
            series.clear();
            i=0;
            System.out.println("Llgue al 10");
        }
    } //No sirvehujj
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        botonComenzar = new javax.swing.JButton();
        BotonParar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        pane.setBackground(new java.awt.Color(204, 255, 255));
        pane.setLayout(new java.awt.BorderLayout());

        botonComenzar.setText("Comenzar");
        botonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComenzarActionPerformed(evt);
            }
        });

        BotonParar.setText("Parar");
        BotonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botonComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(BotonParar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComenzar)
                    .addComponent(BotonParar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComenzarActionPerformed
        // TODO add your handling code here:
        //String dt=
    datos();
    //BotonParar.setVisible(true);
      //holmm nbehfr  
        
      
        
    }//GEN-LAST:event_botonComenzarActionPerformed

    private void BotonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPararActionPerformed
        // TODO add your handling code here:
        this.hide();
        //series.clear();
        
        ///rr
        ///rrr
        
        
    }//GEN-LAST:event_BotonPararActionPerformed

    
    
    public void datasetActionPerformed(java.awt.event.ActionEvent e) {
      
      //if(e.getClickCount()==2){
         BotonParar.setVisible(true);
         //botonComenzar.setVisible(true);
       //}
    }

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonParar;
    private javax.swing.JButton botonComenzar;
    private javax.swing.JPanel pane;
    // End of variables declaration//GEN-END:variables
//Lights On
    @Override
    public void run() {
        
           try{
                //System.out.println("Estoy a la escucha");
                ServerSocket servidor = new ServerSocket(9999);
                String mensaje="";
               //Hilo
                while(true){
                    System.out.println("Esperando conexion");
                Socket misocket = servidor.accept();
                    System.out.println("Conexion aceptada");
                misocket.getLocalPort();
                DataInputStream flujo_entrada = new DataInputStream(misocket.getInputStream());
                mensaje = flujo_entrada.readUTF();
                double a = Double.parseDouble(mensaje);
                System.out.println(a);
                i=i+1;
                series.add(i,1023-a);
                if(i>10){
                    series.clear(); 
                    i=0;
                    System.out.println("LLEGUE HASTA EL 10");
                }
                misocket.close();
                
                }
                
            } catch (IOException ex) {
                //Logger.getLogger(MarcoServidor.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            } 
        
    }

}

//hola
//holarwdv nc nc